stages:
  - build
  - test
  - timings
  - cleanup
  - deploy

############################################
# System templates
############################################

# Windows
.template_windows_32: &win32
  tags:
    - windows
    - x86
  before_script:
    - "echo off"
    - 'call "%VS140COMNTOOLS%\..\..\VC\bin\vcvars32.bat"'
    - set CMAKE_GENERATOR=Visual Studio 14 2015
    - set CI_DIR=C:\ci\%CI_PIPELINE_ID%_32
    - set NETGEN_BUILD_DIR=%CI_DIR%\build
    - set CMAKE_INSTALL_PREFIX=%CI_DIR%\install
    - set NETGENDIR=%CMAKE_INSTALL_PREFIX%\bin
    - set PYTHONPATH=%CMAKE_INSTALL_PREFIX%\lib\site-packages
    - set CMAKE_CONFIG=-DUSE_MKL=OFF -DUSE_OCC=ON

.template_windows_64: &win64
  tags:
    - windows
    - x64
  before_script:
    - "echo off"
    - 'call "%VS140COMNTOOLS%\..\..\VC\vcvarsall" x64'
    - set CMAKE_GENERATOR=Ninja
    - set CI_DIR=C:\ci\%CI_PIPELINE_ID%_64
    - set NETGEN_BUILD_DIR=%CI_DIR%\build
    - set CMAKE_INSTALL_PREFIX=%CI_DIR%\install
    - set NETGENDIR=%CMAKE_INSTALL_PREFIX%\bin
    - set PATH=%NETGENDIR%;%PATH%
    - set PYTHONPATH=%CMAKE_INSTALL_PREFIX%\lib\site-packages
    - set UPLOAD_DIR=/home/tester/deploy/win64/%CI_BUILD_TAG%%CI_BUILD_REF%/
    - set CLCACHE_BASEDIR=%CI_DIR%
    - set CMAKE_CONFIG=-DUSE_OCC=ON -DUSE_CCACHE=ON -DUSE_MKL=ON -DMKL_STATIC=ON -DMKL_ROOT="C:/Intel/compilers_and_libraries/windows/mkl"

# Linux
.template_ubuntu: &ubuntu
  tags:
    - linux
    - docker
  before_script:
    - pwd
    - ls
    - docker info

.template_ubuntu_1604: &ubuntu_1604
  <<: *ubuntu
  variables:
    UBUNTU_VERSION: "16.04"
    UBUNTU_VERSION_NAME: "xenial"

.template_ubuntu_1610: &ubuntu_1610
  <<: *ubuntu
  variables:
    UBUNTU_VERSION: "16.10"
    UBUNTU_VERSION_NAME: "yakkety"

.template_ubuntu_1704: &ubuntu_1704
  <<: *ubuntu
  variables:
    UBUNTU_VERSION: "17.04"
    UBUNTU_VERSION_NAME: "zesty"

.template_ubuntu_1710: &ubuntu_1710
  <<: *ubuntu
  variables:
    UBUNTU_VERSION: "17.10"
    UBUNTU_VERSION_NAME: "artful"

.template_ubuntu_debug: &ubuntu_debug
  <<: *ubuntu
  variables:
    UBUNTU_VERSION: "debug"
    UBUNTU_VERSION_NAME: "debug"

# MacOSX
.template_mac: &mac
  tags:
    - mac
  before_script:
    - export BUILD_DIR=/tmp/$CI_PIPELINE_ID
    - export CMAKE_INSTALL_PREFIX=/tmp/$CI_PIPELINE_ID/install/Netgen.app
    - export MACOSX_DEPLOYMENT_TARGET=10.9
    - export PYTHONPATH=$CMAKE_INSTALL_PREFIX/Contents/Resources/lib/python3.6/site-packages:.
    - export PATH=$CMAKE_INSTALL_PREFIX/Contents/MacOS:$PATH

############################################
# Build stage
############################################

# Windows
.template_build_win: &build_win
  stage: build
  script:
    - git submodule update --init --recursive
    - rd /s /q %NETGEN_BUILD_DIR%
    - mkdir %NETGEN_BUILD_DIR%
    - cd %NETGEN_BUILD_DIR%
    - >-
        cmake %CI_PROJECT_DIR%
        -G"%CMAKE_GENERATOR%"
        -DCMAKE_INSTALL_PREFIX=%CMAKE_INSTALL_PREFIX%
        %CMAKE_CONFIG%
        -DUSE_UMFPACK=ON
        -DENABLE_UNIT_TESTS=ON
        -DCPACK_PACKAGE_NAME=NGSolve${PACKAGE_NAME_SUFFIX}
        -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target install --config Release
    - cmake --build . --target package --config Release
    - >-
      rsync -ztrl --del -e ssh
      --rsync-path="mkdir -p deploy/builds/%CI_PIPELINE_ID%/windows && rsync"
      *.msi
      gitlab-runner@vector.asc.tuwien.ac.at:deploy/builds/%CI_PIPELINE_ID%/windows/

.win32_build:
  <<: *win32
  <<: *build_win

win64_build:
  <<: *win64
  <<: *build_win

# Linux
.template_build_linux: &build_linux
  stage: build
  script:
    - docker build -t ngsolve_${CI_PIPELINE_ID}:$UBUNTU_VERSION -f tests/docker_$UBUNTU_VERSION .
    - rm -f ngsolve_${CI_PIPELINE_ID}_$UBUNTU_VERSION.id
    - >-
      docker run
      --cidfile ngsolve_${CI_PIPELINE_ID}_$UBUNTU_VERSION.id
      -e MKLROOT=/opt/intel/mkl
      -e UBUNTU_VERSION_NAME=$UBUNTU_VERSION_NAME
      -e CI_BUILD_REF=$CI_BUILD_REF
      -e CI_PIPELINE_ID=$CI_PIPELINE_ID
      -e CMAKE_ARGS="-DCPACK_DEBIAN_PACKAGE_NAME=ngsolve${PACKAGE_NAME_SUFFIX}"
      -e CCACHE_DIR=/ccache
      -e SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY"
      -v /opt/intel:/opt/intel
      -v /mnt/ccache:/ccache ngsolve_${CI_PIPELINE_ID}:$UBUNTU_VERSION
      bash /root/src/ngsolve/tests/build.sh
    - docker commit `cat ngsolve_${CI_PIPELINE_ID}_$UBUNTU_VERSION.id` ngsolve_${CI_PIPELINE_ID}_installed:$UBUNTU_VERSION

ubuntu_1604_build:
  <<: *ubuntu_1604
  <<: *build_linux

ubuntu_1610_build:
  <<: *ubuntu_1610
  <<: *build_linux

ubuntu_1704_build:
  <<: *ubuntu_1704
  <<: *build_linux

ubuntu_1710_build:
  <<: *ubuntu_1710
  <<: *build_linux

debug_build:
  <<: *ubuntu_debug
  <<: *build_linux

mac_build:
  <<: *mac
  stage: build
  script:
    - git submodule update --init --recursive
    - rm -rf $BUILD_DIR
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - >-
      cmake $CI_PROJECT_DIR
      -DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX
      -DCMAKE_BUILD_TYPE=Release
      -DUSE_NATIVE_ARCH=OFF
      -DUSE_CCACHE=ON
      -DUSE_UMFPACK=ON
      -DENABLE_UNIT_TESTS=ON
      -DCPACK_PACKAGE_NAME=NGSolve${PACKAGE_NAME_SUFFIX}
    - make -j5 install
    - osascript -e 'tell application "Finder" to eject (every disk whose ejectable is true)'
    - make bundle
    - >-
      rsync -ztrl --del -e ssh
      --rsync-path="mkdir -p deploy/builds/$CI_PIPELINE_ID/macos && rsync"
      *.dmg
      gitlab-runner@vector.asc.tuwien.ac.at:deploy/builds/$CI_PIPELINE_ID/macos/

############################################
# Test stage
############################################

# Windows
.template_test_win: &test_win
  stage: test
  script:
    - cd %NETGEN_BUILD_DIR%/ngsolve
    - ctest -C Release --output-on-failure
    - cd ..

# skip since we have no machine with 32 bits
.test_win32:
  <<: *win32
  <<: *test_win

win64_test:
  <<: *win64
  <<: *test_win

# Linux
.template_test_linux: &test_linux
  stage: test
  script:
    - >-
      docker run
      -e NETGENDIR=/opt/netgen/bin
      -e NGS_NUM_THREADS=6
      -e PYTHONPATH=/opt/netgen/lib/python3/dist-packages
      -e MKLROOT=/opt/intel/mkl
      -e MKL_NUM_THREADS=1
      -e MKL_DOMAIN_THREADS="MKL_DOMAIN_PARDISO=6"
      -e LD_LIBRARY_PATH=/opt/intel/mkl/lib/intel64
      -v /opt/intel:/opt/intel
      ngsolve_${CI_PIPELINE_ID}_installed:$UBUNTU_VERSION
      bash -c 'cd /root/build/ngsolve && make test_ngsolve ARGS="--output-on-failure"'

ubuntu_1604_test:
  <<: *ubuntu_1604
  <<: *test_linux

ubuntu_1610_test:
  <<: *ubuntu_1610
  <<: *test_linux

ubuntu_1704_test:
  <<: *ubuntu_1704
  <<: *test_linux

ubuntu_1710_test:
  <<: *ubuntu_1710
  <<: *test_linux

debug_test:
  <<: *ubuntu_debug
  <<: *test_linux
  allow_failure: true

mac_test:
  <<: *mac
  stage: test
  script:
    - cd $BUILD_DIR/ngsolve
    - ctest . --output-on-failure

############################################
# Timings stage
############################################

.t_clang: &t_clang
  variables:
    CMAKE_C_COMPILER: "clang"
    CMAKE_CXX_COMPILER: "clang++"

.t_gcc7: &t_gcc7
  variables:
    CMAKE_C_COMPILER: "gcc-7"
    CMAKE_CXX_COMPILER: "g++-7"

.t_gcc6: &t_gcc6
  variables:
    CMAKE_C_COMPILER: "gcc-6"
    CMAKE_CXX_COMPILER: "g++-6"

.t_gcc5: &t_gcc5
  variables:
    CMAKE_C_COMPILER: "gcc-5"
    CMAKE_CXX_COMPILER: "g++-5"

.t_omit_frame_pointer: &t_omit_frame_pointer
  before_script:
    - export CMAKE_FLAGS="-fomit-frame-pointer"

.t_timings: &t_timings
  allow_failure: true
  stage: timings
  tags:
    - linux
    - avx2
  only:
    - triggers
  script:
    - git submodule update --init --recursive
    - mkdir build
    - mkdir install
    - cd build
    - >-
        cmake ..
        -DUSE_CCACHE=ON
        -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/install
        -DUSE_NATIVE_ARCH=ON
        -DCMAKE_C_COMPILER=$CMAKE_C_COMPILER
        -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER
        -DCMAKE_CXX_FLAGS="-ffast-math $CMAKE_FLAGS"
        -DUSE_MKL=ON
        -DMKL_ROOT=/opt/intel/mkl
        -DCMAKE_BUILD_TYPE=Release
    - make -j install
    - export NETGENDIR=$CI_PROJECT_DIR/install/bin
    - export PATH=$CI_PROJECT_DIR/install/bin:$PATH
    - export PYTHONPATH=$CI_PROJECT_DIR/install/lib/python3.6/site-packages:.
    - export LD_LIBRARY_PATH=$CI_PROJECT_DIR/install/lib:.:$LD_LIBRARY_PATH
    - cd ngsolve
    - if [ -n "${RUN_TIMINGS}" ]; then make timings; fi

  artifacts:
    paths:
      - build/ngsolve/tests/timings/results.json

gcc5_timings:
  <<: *t_gcc5
  <<: *t_timings

gcc6_timings:
  <<: *t_gcc6
  <<: *t_timings

gcc7_timings:
  <<: *t_gcc7
  <<: *t_timings

clang_timings:
  <<: *t_clang
  <<: *t_timings

clang_no_fp_timings:
  <<: *t_omit_frame_pointer
  <<: *t_clang
  <<: *t_timings

############################################
# Cleanup stage
############################################

linux_cleanup:
  stage: cleanup
  tags:
    - linux
    - docker
  script:
    # remove built docker images
    - docker ps -a | awk '{ print $1,$2 }' | grep ngsolve_${CI_PIPELINE_ID} | awk '{print $1 }' | xargs -I {} docker rm {} || true
    - docker rmi -f ngsolve_${CI_PIPELINE_ID}:16.04 || true
    - docker rmi -f ngsolve_${CI_PIPELINE_ID}_installed:16.04 || true
    - docker rmi -f ngsolve_${CI_PIPELINE_ID}:16.10 || true
    - docker rmi -f ngsolve_${CI_PIPELINE_ID}_installed:16.10 || true
    - docker rmi -f ngsolve_${CI_PIPELINE_ID}:17.04 || true
    - docker rmi -f ngsolve_${CI_PIPELINE_ID}_installed:17.04 || true
    - docker rmi -f ngsolve_${CI_PIPELINE_ID}:17.10 || true
    - docker rmi -f ngsolve_${CI_PIPELINE_ID}_installed:17.10 || true
    - docker rmi -f ngsolve_${CI_PIPELINE_ID}:debug || true
    - docker rmi -f ngsolve_${CI_PIPELINE_ID}_installed:debug || true
  when: always
  allow_failure: true

win64_cleanup:
  <<: *win64
  stage: cleanup
  tags:
    - windows
    - x64
  script:
    - cd %CI_PROJECT_DIR%
    - rd /s /q %CI_DIR%
  when: always
  allow_failure: true

.win32_cleanup:
  <<: *win32
  stage: cleanup
  tags:
    - windows
    - x86
  script:
    - cd %CI_PROJECT_DIR%
    - rd /s /q %CI_DIR%
  when: always
  allow_failure: true

cleanup_mac:
  <<: *mac
  stage: cleanup
  script:
    - rm -rf $BUILD_DIR
  when: always
  allow_failure: true

############################################
# Deploy stage
############################################

deploy_github:
  stage: deploy
  tags:
    - linux
    - docker
  script:
    - git remote add github git@github.com:NGSolve/ngsolve.git || true
    - git remote update
    - git checkout master
    - git pull origin master
    - git push github master
  only:
    - master

deploy_release:
  stage: deploy
  tags:
    - linux
    - docker
  script:
    - /home/gitlab-runner/deploy/deploy_release.sh $CI_PIPELINE_ID $CI_BUILD_TAG
  only:
    - tags
  environment: deploy_release

deploy_nightly:
  stage: deploy
  tags:
    - linux
    - docker
  script:
    - if [ -n "${RUN_DEPLOY}" ]; then /home/gitlab-runner/deploy/deploy_nightly.sh $CI_PIPELINE_ID; fi
  only:
    - triggers
  except:
    - tags
  environment: deploy_nigthly
